coverage:
  range: 60..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    #patch: off

ignore:
  - "**/coverage"
  - "**/tests*"
  - "**/conftest.py"
  - "**/benchmarks*"